from argparse import ArgumentParser
from pathlib import Path
from time import time as now

verbose = False

def log(*args):
    global verbose

    if verbose:
        print(*args)

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument("src_dir", type=Path)
    parser.add_argument("dst_dir", type=Path)
    parser.add_argument("timestamp", type=Path)

    args = parser.parse_args()

    scr_dir = args.src_dir
    dst_dir = args.dst_dir
    timestamp_path = args.timestamp

    # Copy new assets
    for asset in scr_dir.rglob("*"):
        if not asset.is_file() or asset.suffix == ".blend":
            continue

        dst_asset = dst_dir / asset.relative_to(scr_dir)

        if not dst_asset.exists() or asset.stat().st_mtime > dst_asset.stat().st_mtime:
            dst_asset.parent.mkdir(exist_ok=True, parents=True)
            asset.copy(dst_asset)
            log("copying", asset)
        else:
            log("skipping", asset)

    # Clear deleted assets
    dirs_to_check = []
    for asset in dst_dir.rglob("*"):
        if not asset.is_file():
            continue

        if not (scr_dir / asset.relative_to(dst_dir)).exists():
            log("deleting", asset)
            asset.unlink()
            dirs_to_check.append(asset.parent)

    while len(dirs_to_check) > 0:
        directory = dirs_to_check.pop(0)

        if not directory.exists():
            continue

        if not any(directory.iterdir()):
            log("deleting", asset)
            directory.rmdir()
            dirs_to_check.append(directory.parent)

    # Save copy time
    with timestamp_path.open("w") as file:
        file.write(f"Generated by {__file__} on {now()}")
